### ISSUE TITLE
Allow two modes in the storage module

### ISSUE THREAD

**Issue by GauravTalreja** [GauravTalreja/ebb#9]
# Implementation

- Use an env variable to determine which "mode" the storage module is running in, sample or prod (name it appropriately, this is not an `APP_MODE` but just for the storage module)
- Place prod and sample queries in separate folders
- Use the ``sqlx::query_file!`` macro in the storage module, in which the mode is used to append the folder name to the base query file
- These modes should only affect the storage module, the rest of the app should not be coupled with the storage mode
- Note: You don't need to implement any queries here, we just need a quick hello world for the two modes.

Rubric requirements (for reference, writing these queries requires two modes):

- **C3**. SQL queries for features, test-sample.sql, test-sample.out A file test-sample.sql (or other corresponding files) containing the SQL statements, and a file test-sample.out showing the results of running test-sample.sql over your sample database. 
- **C4**. SQL queries for features, test-production.sql, test-production.out A file test-production.sql (or other corresponding files) containing the SQL statements, and a file test-production.out showing the results of running test-production.sql over your production database. 

# Report Writing
-  **R3**. Database with sample dataset: A description of the sample data, how the data is generated/cleaned/imported for your application, and how to use the data to populate your database. 

- **R4**. Database with production dataset: A description of the production data, how the data is generated/cleaned/imported for your application, and how to use the data to populate your database.

**Comment by GauravTalreja** [comment]
@SallyHong2347 Feel free to take up the report writing parts if you'd like. We need **R3** for milestone 1 and you can add it directly to typst or just leave a comment with the write up here.

**Comment by Justin-Kwan** [comment]
Won't have cycles for this. @PatelProjects Please TAL when you can
